server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /health {
    proxy_pass http://broker-server:3001;
  }

  location /alerts {
    proxy_pass http://broker-server:3001;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
